Repository hpi-swt2/vm-portal, pull requests merged in 2018-11, with the labels that each got.

#44 Add VM-Request reject and accept functionality
  app/controllers/requests_controller.rb
  app/helpers/requests_helper.rb
  app/models/request.rb
  app/views/requests/_form.html.erb
  app/views/requests/_request.json.jbuilder
  app/views/requests/index.html.erb
  app/views/requests/show.html.erb
  db/migrate/20181113194553_create_requests.rb
  db/schema.rb
  spec/factories/requests.rb
  spec/views/requests/edit.html.erb_spec.rb
  spec/views/requests/index.html.erb_spec.rb
  spec/views/requests/new.html.erb_spec.rb
  spec/views/requests/show.html.erb_spec.rb
Labels: team scaffold

#43 Add VM and Server List
  app/api/vmapi.rb
  app/controllers/vm_controller.rb
  app/views/vm/index.html.erb
  spec/api/apiwrapper_spec.rb
  spec/controllers/vm_controller_spec.rb
  spec/views/vm/index.html.erb_spec.rb
Labels: team resource overview

#92 Merge resource-dev into dev branch
  app/api/vmapi.rb
  app/controllers/vm_controller.rb
  app/views/vm/index.html.erb
  app/views/vm/show.html.erb
  app/views/vm/show_host.html.erb
  config/routes.rb
  spec/api/apiwrapper_spec.rb
  spec/controllers/vm_controller_spec.rb
  spec/views/vm/index.html.erb_spec.rb
  spec/views/vm/show.html.erb_spec.rb
  spec/views/vm/show_host.html.erb_spec.rb
Labels: team resource overview

#124 Remove Details Button, add Timeslot Button
  app/views/server/index.html.erb
  app/views/server/show.html.erb
  app/views/vm/index.html.erb
  spec/views/server/index.html.erb_spec.rb
  spec/views/server/show.html.erb_spec.rb
  spec/views/vm/index.html.erb_spec.rb
Labels: Review Required
