Repository hpi-swt2/vm-portal, pull requests merged in 2018-12, with the labels that each got.

#130 Restful Paths
  Gemfile
  app/assets/javascripts/vms.coffee
  app/assets/stylesheets/vms.scss
  app/controllers/application_controller.rb
  app/controllers/vms_controller.rb
  app/helpers/vms_helper.rb
  app/views/server/index.html.erb
  app/views/server/show.html.erb
  app/views/vm/edit.html.erb
  app/views/vms/edit.html.erb
  app/views/vms/index.html.erb
  app/views/vms/new.html.erb
  app/views/vms/show.html.erb
  config/deploy.rb
  config/routes.rb
  db/schema.rb
  spec/controllers/vms_controller_spec.rb
  spec/routing/requests_routing_spec.rb
  spec/views/vms/index.html.erb_spec.rb
  spec/views/vms/new.html.erb_spec.rb
  spec/views/vms/show.html.erb_spec.rb
Labels: Review Required

#129 fix/scaffold/request-form-adjustments
  app/controllers/requests_controller.rb
  app/views/requests/_form.html.erb
  app/views/requests/_request.json.jbuilder
  app/views/requests/index.html.erb
  app/views/requests/show.html.erb
  db/migrate/20181130145113_remove_software_from_requests.rb
  db/schema.rb
  spec/controllers/requests_controller_spec.rb
  spec/factories/requests.rb
  spec/views/requests/edit.html.erb_spec.rb
  spec/views/requests/index.html.erb_spec.rb
  spec/views/requests/new.html.erb_spec.rb
  spec/views/requests/show.html.erb_spec.rb
Labels: Review Required

#125 Deleted/Added links on requests index/show page (#57)
  app/views/requests/index.html.erb
  app/views/requests/show.html.erb
Labels: Review Required

#133 VM Request form adjustments and project layout fix
  app/assets/stylesheets/requests.scss
  app/assets/stylesheets/scaffolds.scss
  app/views/requests/_form.html.erb
  spec/views/requests/edit.html.erb_spec.rb
  spec/views/requests/new.html.erb_spec.rb
Labels: Review Required

#140 issue 72 rename reserve button
  app/views/servers/show.html.erb
  spec/views/servers/show.html.erb_spec.rb
Labels: Review Required, enhancement

#142 47/oldies/handle hpi network errors
  Gemfile
  Gemfile.lock
  app/api/vmapi.rb
  app/controllers/application_controller.rb
  app/controllers/servers_controller.rb
  app/controllers/vms_controller.rb
  app/views/errors/timeout.html.erb
  app/views/servers/index.html.erb
  app/views/servers/show.html.erb
  app/views/vms/index.html.erb
  app/views/vms/show.html.erb
  db/schema.rb
  spec/controllers/servers_controller_spec.rb
  spec/controllers/vms_controller_spec.rb
Labels: Review Required

#157 applied some style; should fix #59
  app/assets/stylesheets/requests.scss
  app/views/requests/_form.html.erb
  app/views/requests/index.html.erb
  app/views/requests/show.html.erb
Labels: Review Required

#134 14/scaffold/slack user notification
  app/assets/javascripts/slack.coffee
  app/assets/stylesheets/slack.scss
  app/controllers/requests_controller.rb
  app/controllers/slack_controller.rb
  app/helpers/slack_helper.rb
  app/models/request.rb
  app/models/slack_auth_request.rb
  app/models/slack_hook.rb
  app/models/user.rb
  app/views/slack/new.html.erb
  app/views/slack/update.html.erb
  config/routes.rb
  db/migrate/20181128142014_create_slack_auth_requests.rb
  db/migrate/20181128151612_create_slack_hooks.rb
  db/schema.rb
  spec/factories/slack_auth_requests.rb
  spec/factories/slack_hooks.rb
  spec/features/slack/slack_controller_spec.rb
  spec/helpers/slack_helper_spec.rb
Labels: Review Required

#162 The redirect_uri for the slack calls now adapts to the base_url the page was opened with
  app/controllers/slack_controller.rb
  db/schema.rb
Labels: Review Required

#138 99/scaffold - add table to add users in requests
  app/controllers/application_controller.rb
  app/controllers/requests_controller.rb
  app/controllers/users/registrations_controller.rb
  app/models/request.rb
  app/models/user.rb
  app/models/users_assigned_to_request.rb
  app/views/requests/_form.html.erb
  app/views/requests/show.html.erb
  db/migrate/20181207115117_merge_user_and_user_profile.rb
  db/migrate/20181209184959_create_users_assigned_to_requests.rb
  db/schema.rb
  spec/factories/users_assigned_to_requests.rb
  spec/models/users_assigned_to_request_spec.rb
Labels: Review Required, WIP

#103 Add notification page. #63
  app/assets/javascripts/notifications.coffee
  app/assets/stylesheets/notifications.scss
  app/controllers/notifications_controller.rb
  app/helpers/notifications_helper.rb
  app/models/notification.rb
  app/views/notifications/_form.html.erb
  app/views/notifications/index.html.erb
  app/views/notifications/new.html.erb
  config/routes.rb
  db/migrate/20181126100931_create_notifications.rb
  db/schema.rb
  spec/factories/notifications.rb
  spec/features/notifications/notifications_spec.rb
Labels: team frontend

#187 refresh look of vm and host details pages (#169 #170)
  app/assets/javascripts/application.js
  app/assets/javascripts/doughnut_chart.js
  app/assets/stylesheets/requests.scss
  app/assets/stylesheets/resource_allocation.scss
  app/controllers/hosts_controller.rb
  app/controllers/vms_controller.rb
  app/views/errors/not_found.html.erb
  app/views/hosts/show.html.erb
  app/views/requests/index.html.erb
  app/views/requests/show.html.erb
  app/views/templates/_hardware_table.html.erb
  app/views/templates/_resource_allocation.html.erb
  app/views/vms/show.html.erb
  spec/controllers/hosts_controller_spec.rb
  spec/controllers/vms_controller_spec.rb
  spec/views/hosts/show.html.erb_spec.rb
  spec/views/templates/_resource_allocation.hml.erb_spec.rb
  spec/views/vms/show.html.erb_spec.rb
Labels: Review Required

#156 33 HPI Login
  .gitignore
  .ruby-version
  Gemfile
  Gemfile.lock
  README.md
  app/controllers/users/omniauth_callbacks_controller.rb
  app/models/user.rb
  app/views/devise/sessions/new.html.erb
  config/environments/development.rb
  config/environments/production.rb
  config/environments/test.rb
  config/initializers/devise.rb
  config/routes.rb
  db/migrate/20181206152910_add_omniauth_to_users.rb
  db/migrate/20181207120127_add_user_id_to_user.rb
  db/schema.rb
  spec/features/sessions/user_sign_in_spec.rb
  spec/models/user_spec.rb
Labels: Review Required, team login

#195 Add Privacy Policy
  PrivacyPolicy.md
Labels: Review Required

#165 98/scaffold/vm template creation
  app/assets/javascripts/request_templates.coffee
  app/assets/stylesheets/request_templates.scss
  app/controllers/request_templates_controller.rb
  app/controllers/slack_controller.rb
  app/helpers/request_templates_helper.rb
  app/models/request_template.rb
  app/views/request_templates/_form.html.erb
  app/views/request_templates/_request_template.json.jbuilder
  app/views/request_templates/edit.html.erb
  app/views/request_templates/index.html.erb
  app/views/request_templates/index.json.jbuilder
  app/views/request_templates/new.html.erb
  app/views/request_templates/show.html.erb
  app/views/request_templates/show.json.jbuilder
  app/views/requests/index.html.erb
  config/routes.rb
  db/migrate/20181207093210_create_request_templates.rb
  db/migrate/20181207094454_add_name_to_request_template.rb
  db/schema.rb
  spec/controllers/request_templates_controller_spec.rb
  spec/factories/request_templates.rb
  spec/features/slack/slack_controller_spec.rb
  spec/helpers/request_templates_helper_spec.rb
  spec/requests/request_templates_spec.rb
  spec/routing/request_templates_routing_spec.rb
  spec/views/request_templates/edit.html.erb_spec.rb
  spec/views/request_templates/index.html.erb_spec.rb
  spec/views/request_templates/new.html.erb_spec.rb
  spec/views/request_templates/show.html.erb_spec.rb
Labels: Review Required

#188 95/scaffold/add ports to requests
  app/controllers/requests_controller.rb
  app/views/requests/_form.html.erb
  app/views/requests/index.html.erb
  app/views/requests/show.html.erb
  config/database.yml
  db/migrate/20181113194553_create_requests.rb
  db/schema.rb
  spec/views/requests/edit.html.erb_spec.rb
  spec/views/requests/index.html.erb_spec.rb
  spec/views/requests/new.html.erb_spec.rb
  spec/views/requests/show.html.erb_spec.rb
Labels: Review Required

#202 155/scaffold custom redirection after vm request creation
  app/controllers/requests_controller.rb
  spec/controllers/requests_controller_spec.rb
Labels: Review Required

#184 66/frontend/notifications item in header
  app/assets/javascripts/notifications.coffee
  app/assets/stylesheets/notifications.scss
  app/controllers/notifications_controller.rb
  app/views/application/_navbar.html.erb
  config/routes.rb
  spec/features/notifications/notifications_spec.rb
Labels: team frontend

#214 get rid of table layout on VM and host detail pages
  app/assets/javascripts/application.js
  app/assets/javascripts/doughnut_chart.js
  app/assets/stylesheets/resource_allocation.scss
  app/assets/stylesheets/vms.scss
  app/views/hosts/show.html.erb
  app/views/templates/_resource_allocation.html.erb
  app/views/vms/show.html.erb
Labels: Review Required

#215 rename accept button
  app/views/requests/show.html.erb
  db/schema.rb
  spec/features/requests/accept_reject_request_spec.rb
Labels: Review Required

#197 Move "add to slack" button to user page
  app/controllers/requests_controller.rb
  app/controllers/slack_controller.rb
  app/models/request.rb
  app/views/slack/new.html.erb
  app/views/users/show.html.erb
Labels: Review Required
