Repository hpi-swt2/vm-portal, pull requests merged in 2019-04, with the labels that each got.

#525 Use Bootstrap form builder
  Gemfile
  Gemfile.lock
  app/assets/javascripts/request.js
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/select2-custom.scss
  app/controllers/projects_controller.rb
  app/controllers/requests_controller.rb
  app/helpers/hart_form_builder.rb
  app/helpers/operating_systems_helper.rb
  app/models/project.rb
  app/models/request.rb
  app/models/request_template.rb
  app/models/user.rb
  app/views/app_settings/_form.html.erb
  app/views/operating_systems/_form.html.erb
  app/views/projects/_form.html.erb
  app/views/projects/edit.html.erb
  app/views/projects/new.html.erb
  app/views/request_templates/_form.html.erb
  app/views/requests/_form.html.erb
  app/views/servers/_form.html.erb
  app/views/users/edit.html.erb
  app/views/vms/edit.html.erb
  app/views/vms/edit_config.html.erb
  config/locales/en.yml
  spec/end_to_end/end_to_end_spec.rb
  spec/features/projects/edit.html.erb_spec.rb
  spec/features/projects/new.html.erb_spec.rb
  spec/features/requests/select_operating_system_spec.rb
  spec/features/users/edit.html.erb_spec.rb
  spec/helpers/operating_systems_helper_spec.rb
  spec/models/request_spec.rb
  spec/models/request_templates_spec.rb
  spec/views/requests/new.html.erb_spec.rb
Labels: Review Required, merge when green

#539 Massively speed up tests
  spec/factories/users.rb
Labels: Review Required

#517 Faster loading of dashboard and vms/index page
  Gemfile
  Gemfile.lock
  app/api/v_sphere/folder.rb
  app/api/v_sphere/virtual_machine.rb
  app/helpers/vms_helper.rb
  app/views/vms/_table.erb
  db/schema.rb
  spec/api/v_sphere_api_mocker.rb
  spec/api/v_sphere_api_spec.rb
Labels: Review Required

#523 Show Puppet Scripts on VMs#show
  app/controllers/vms_controller.rb
  app/models/app_setting.rb
  app/models/virtual_machine_config.rb
  app/views/application/_modal.html.erb
  app/views/requests/_detail.html.erb
  app/views/requests/index.html.erb
  app/views/requests/show.html.erb
  app/views/vms/show.html.erb
  spec/views/vms/show.html.erb_spec.rb
Labels: Review Required

#529 515/better error handling
  app/helpers/hart_formatter.rb
  app/models/notification.rb
  app/models/user.rb
  app/views/notifications/_list.html.erb
  config/application.rb
  config/environments/production.rb
  db/migrate/20190327182939_add_type_to_notifications.rb
  db/migrate/20190406192841_add_count_to_notifications.rb
  db/schema.rb
  spec/factories/notifications.rb
  spec/helpers/hart_formatter_spec.rb
  spec/models/user_spec.rb
  spec/views/notifications/_list.html.erb_spec.rb
Labels: Review Required

#542 Bugfix: To many files open
  app/api/v_sphere/connection.rb
Labels: Review Required

#532 401/user management for servers
  app/controllers/servers_controller.rb
  app/models/machine.rb
  app/models/server.rb
  app/models/virtual_machine_config.rb
  app/views/servers/_form.html.erb
  app/views/servers/edit.html.erb
  app/views/servers/show.html.erb
  spec/controllers/servers_controller_spec.rb
  spec/models/server_spec.rb
Labels: merge when green
