Repository hpi-swt2/vm-portal, pull requests merged in 2019-03, with the labels that each got.

#418 262/filter search all users page
  README.md
  app/assets/javascripts/application.js
  app/assets/javascripts/filter_table.js
  app/assets/javascripts/sort_table.js
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/application/custom_bootstrap.scss
  app/assets/stylesheets/application/filter-box.scss
  app/assets/stylesheets/application/table.scss
  app/assets/stylesheets/layout.scss
  app/assets/stylesheets/vms.scss
  app/views/application/_footer.html.erb
  app/views/hosts/index.html.erb
  app/views/requests/index.html.erb
  app/views/servers/index.html.erb
  app/views/users/index.html.erb
  app/views/vms/index.html.erb
  spec/controllers/users_controller_spec.rb
  spec/features/users/index.html.erb_spec.rb
Labels: Review Required

#436 admins can configure ip and dns of vms
  app/controllers/vms_controller.rb
  app/views/vms/edit.html.erb
  spec/views/vms/edit.html.erb_spec.rb
Labels: Review Required

#420 #405#406/dashboard and vm-overview refactoring
  app/assets/javascripts/filter_table.js
  app/assets/stylesheets/vms.scss
  app/controllers/dashboard_controller.rb
  app/controllers/notifications_controller.rb
  app/controllers/projects_controller.rb
  app/controllers/requests_controller.rb
  app/controllers/users_controller.rb
  app/controllers/vms_controller.rb
  app/helpers/vms_helper.rb
  app/jobs/application_job.rb
  app/models/request.rb
  app/models/user.rb
  app/views/application/_navbar.html.erb
  app/views/dashboard/_widget.erb
  app/views/dashboard/index.html.erb
  app/views/hosts/index.html.erb
  app/views/notifications/_list.html.erb
  app/views/requests/_form.html.erb
  app/views/requests/index.html.erb
  app/views/servers/index.html.erb
  app/views/users/index.html.erb
  app/views/vms/_archive_buttons.erb
  app/views/vms/_revive_buttons.erb
  app/views/vms/_section.erb
  app/views/vms/_table.erb
  app/views/vms/_to_revive_buttons.erb
  app/views/vms/_vm_status.html.erb
  app/views/vms/index.html.erb
  app/views/vms/show.html.erb
  config/routes.rb
  db/migrate/20190227101842_add_link_to_notification.rb
  db/schema.rb
  spec/controllers/notifications_controller_spec.rb
  spec/end_to_end/end_to_end_spec.rb
  spec/features/dashboard/dashboard_spec.rb
  spec/features/notifications/notifications_spec.rb
  spec/spec_helper.rb
  spec/support/redirect_back.rb
  spec/views/vms/index.html.erb_spec.rb
Labels: Review Required

#441 424/Ensure correct format for VM names
  app/controllers/requests_controller.rb
  app/helpers/requests_helper.rb
  app/models/request.rb
  lib/puppetscript.rb
  spec/controllers/vms_controller_spec.rb
  spec/factories/requests.rb
  spec/helpers/requests_helper_spec.rb
  spec/models/request_spec.rb
  spec/models/user_spec.rb
  spec/views/requests/index.html.erb_spec.rb
  spec/views/requests/show.html.erb_spec.rb
Labels: Review Required

#456 451/Redirect to configs page after reviving
  app/controllers/vms_controller.rb
Labels: Review Required

#458 458/450/RefactorVMPages
  app/views/dashboard/index.html.erb
  app/views/vms/_running_vm_buttons.erb
  app/views/vms/_table.erb
  app/views/vms/_vm_confirmations.erb
  app/views/vms/index.html.erb
  spec/views/vms/index.html.erb_spec.rb
Labels: Review Required

#457 452/Update design of config edit page
  Gemfile
  Gemfile.lock
  app/assets/javascripts/application.js
  app/views/vms/edit_config.html.erb
Labels: Review Required

#471 455/Handle error when reading puppet files with unsupported format
  app/api/v_sphere/virtual_machine.rb
  app/helpers/application_helper.rb
  spec/api/v_sphere/virtual_machine_spec.rb
Labels: Review Required

#472 449/created VMs in wrong network
  app/api/v_sphere/cluster.rb
  app/api/v_sphere/folder.rb
  app/models/request.rb
  app/views/layouts/_flash_message.html.erb
  app/views/requests/show.html.erb
  spec/api/v_sphere_api_mocker.rb
  spec/controllers/requests_controller_spec.rb
Labels: Review Required

#440 430/Refactor buttons
  app/assets/helpers/hart_form_builder.rb
  app/views/requests/_form.html.erb
  app/views/requests/show.html.erb
  app/views/vms/_vm_status.html.erb
  db/schema.rb
Labels: Review Required

#479 Use a better green
  app/assets/stylesheets/application/custom_bootstrap.scss
Labels: Review Required

#464 #463/routes refactor
  config/routes.rb
Labels: Review Required

#481 432/show vSphere path in VMs show
  app/api/v_sphere/folder.rb
  app/api/v_sphere/virtual_machine.rb
  app/models/app_setting.rb
  app/models/server.rb
  app/views/vms/show.html.erb
  spec/api/v_sphere_api_mocker.rb
Labels: Review Required

#482 408/GitBranchSelection
  app/api/v_sphere/virtual_machine.rb
  app/controllers/app_settings_controller.rb
  app/models/app_setting.rb
  app/models/request.rb
  app/models/user.rb
  app/views/app_settings/_form.html.erb
  db/migrate/20190316165741_add_git_branch_to_app_settings.rb
  db/schema.rb
  lib/git_helper.rb
  spec/support/git_stub.rb
Labels: Review Required

#486 476/Move HART Form builder to view helper directory
  app/helpers/hart_form_builder.rb
  app/views/app_settings/_form.html.erb
  app/views/requests/_form.html.erb
  app/views/vms/edit.html.erb
  app/views/vms/edit_config.html.erb
Labels: Review Required

#473 425/v sphere vm name
  app/api/v_sphere/folder.rb
  app/api/v_sphere/virtual_machine.rb
  app/controllers/app_settings_controller.rb
  app/controllers/dashboard_controller.rb
  app/helpers/dashboard_helper.rb
  app/views/app_settings/_form.html.erb
  app/views/dashboard/index.html.erb
  db/migrate/20190318170254_add_max_shown_vms.rb
  db/schema.rb
  db/seeds.rb
Labels: Review Required

#483 427/User-hierarchy
  app/models/request.rb
  app/views/requests/_form.html.erb
  spec/models/request_spec.rb
Labels: Review Required

#475 Layout changes for index pages
  Gemfile
  app/assets/javascripts/application.js
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/application/custom_bootstrap.scss
  app/assets/stylesheets/application/filter-box.scss
  app/assets/stylesheets/application/table.scss
  app/assets/stylesheets/layout.scss
  app/assets/stylesheets/vms.scss
  app/views/hosts/index.html.erb
  app/views/projects/index.html.erb
  app/views/requests/index.html.erb
  app/views/servers/index.html.erb
  app/views/vms/_archive_buttons.erb
  app/views/vms/_revive_buttons.erb
  app/views/vms/_running_vm_buttons.erb
  app/views/vms/_table.erb
  app/views/vms/_to_revive_buttons.erb
  app/views/vms/index.html.erb
  spec/end_to_end/end_to_end_spec.rb
  spec/views/vms/index.html.erb_spec.rb
Labels: Review Required

#493 447/generatePuppetScriptsWithTemplating
  lib/puppetscript.rb
  lib/templates/initScript.pp.erb
  lib/templates/nameScript.pp.erb
  lib/templates/nodeScript.pp.erb
  lib/templates/userScript.pp.erb
  spec/models/request_spec.rb
Labels: Review Required

#495 Address layout issues in VM index
  app/assets/stylesheets/vms.scss
  app/views/users/index.html.erb
  app/views/vms/_archive_buttons.erb
  app/views/vms/_revive_buttons.erb
  app/views/vms/_table.erb
  app/views/vms/_to_revive_buttons.erb
Labels: Review Required

#484 480/Cleanup tests
  app/api/v_sphere/virtual_machine.rb
  app/models/app_setting.rb
  spec/api/v_sphere/virtual_machine_spec.rb
  spec/api/v_sphere_api_mocker.rb
  spec/api/v_sphere_api_spec.rb
  spec/controllers/dashboard_controller_spec.rb
  spec/controllers/vms_controller_spec.rb
  spec/end_to_end/end_to_end_spec.rb
  spec/factories/app_settings.rb
  spec/features/dashboard/dashboard_spec.rb
  spec/helpers/app_settings_helper_spec.rb
  spec/helpers/request_templates_helper_spec.rb
  spec/helpers/servers_helper_spec.rb
  spec/mailers/notification_mailer_spec.rb
  spec/models/app_setting_spec.rb
  spec/models/users_assigned_to_request_spec.rb
  spec/views/vms/index.html.erb_spec.rb
Labels: Review Required

#496 Move to datatables usage
  Gemfile
  Gemfile.lock
  app/assets/javascripts/application.js
  app/assets/javascripts/datatables.js
  app/assets/javascripts/filter_table.js
  app/assets/javascripts/sort_table.js
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/requests.scss
  app/assets/stylesheets/vms.scss
  app/views/application/_footer.html.erb
  app/views/dashboard/_widget.erb
  app/views/hosts/index.html.erb
  app/views/operating_systems/index.html.erb
  app/views/projects/_list.html.erb
  app/views/projects/_table.html.erb
  app/views/projects/index.html.erb
  app/views/projects/show.html.erb
  app/views/request_templates/_form.html.erb
  app/views/request_templates/index.html.erb
  app/views/requests/index.html.erb
  app/views/requests/show.html.erb
  app/views/servers/index.html.erb
  app/views/users/index.html.erb
  app/views/users/show.html.erb
  app/views/vms/_archive_buttons.erb
  app/views/vms/_revive_buttons.erb
  app/views/vms/_running_vm_buttons.erb
  app/views/vms/_section.erb
  app/views/vms/_table.erb
  app/views/vms/_to_revive_buttons.erb
  app/views/vms/index.html.erb
  spec/views/request_templates/index.html.erb_spec.rb
  spec/views/vms/index.html.erb_spec.rb
Labels: Review Required

#506 491/Conform-to-rails-standard
  app/api/v_sphere/virtual_machine.rb
  app/controllers/vms_controller.rb
  app/helpers/vms_helper.rb
  app/models/virtual_machine_config.rb
  app/views/vms/edit.html.erb
  db/schema.rb
  spec/controllers/vms_controller_spec.rb
  spec/helpers/vms_helper_spec.rb
  spec/spec_helper.rb
  spec/views/vms/edit.html.erb_spec.rb
Labels: Review Required

#501 Notification rework
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/notifications.scss
  app/controllers/dashboard_controller.rb
  app/controllers/notifications_controller.rb
  app/controllers/requests_controller.rb
  app/controllers/users_controller.rb
  app/controllers/vms_controller.rb
  app/views/dashboard/index.html.erb
  app/views/notifications/_form.html.erb
  app/views/notifications/_list.html.erb
  app/views/notifications/index.html.erb
  app/views/notifications/new.html.erb
  config/routes.rb
  spec/controllers/notifications_controller_spec.rb
  spec/factories/notifications.rb
  spec/features/dashboard/dashboard_spec.rb
  spec/features/notifications/notifications_spec.rb
Labels: WIP

#502 488/DeleteProjects
  app/controllers/projects_controller.rb
  app/controllers/servers_controller.rb
  app/models/project.rb
  app/views/projects/_table.html.erb
  app/views/projects/show.html.erb
  config/routes.rb
  spec/views/projects/show.html.erb_spec.rb
Labels: Review Required

#498 Standardize styling
  Gemfile
  app/assets/javascripts/app_settings.coffee
  app/assets/javascripts/application.js
  app/assets/javascripts/dashboard.coffee
  app/assets/javascripts/landing.coffee
  app/assets/javascripts/operating_systems.coffee
  app/assets/javascripts/request_templates.coffee
  app/assets/javascripts/requests.coffee
  app/assets/javascripts/servers.coffee
  app/assets/javascripts/slack.coffee
  app/assets/javascripts/users.coffee
  app/assets/javascripts/vms.coffee
  app/assets/stylesheets/app_settings.scss
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/charts.scss
  app/assets/stylesheets/custom.scss
  app/assets/stylesheets/dashboard.scss
  app/assets/stylesheets/datatables-custom.scss
  app/assets/stylesheets/landing.scss
  app/assets/stylesheets/notifications.scss
  app/assets/stylesheets/operating_systems.scss
  app/assets/stylesheets/request_templates.scss
  app/assets/stylesheets/requests.scss
  app/assets/stylesheets/select2-custom.scss
  app/assets/stylesheets/servers.scss
  app/assets/stylesheets/slack.scss
  app/assets/stylesheets/users.scss
  app/assets/stylesheets/vms.scss
  app/views/dashboard/_widget.erb
  app/views/dashboard/index.html.erb
  app/views/operating_systems/_form.html.erb
  app/views/projects/_form.html.erb
  app/views/request_templates/_form.html.erb
  app/views/request_templates/edit.html.erb
  app/views/request_templates/show.html.erb
  app/views/requests/_form.html.erb
  app/views/servers/_form.html.erb
  app/views/servers/new.html.erb
Labels: Review Required

#520 Remove json responses from controllers
  app/controllers/app_settings_controller.rb
  app/controllers/operating_systems_controller.rb
  app/controllers/request_templates_controller.rb
Labels: Review Required

#505 443/Refactoring
  app/controllers/dashboard_controller.rb
Labels: merge when green

#528 Remove Selenium gems
  Gemfile
  Gemfile.lock
  spec/rails_helper.rb
Labels: merge when green

#530 Flash message standardization
  app/controllers/app_settings_controller.rb
  app/controllers/notifications_controller.rb
  app/controllers/operating_systems_controller.rb
  app/controllers/projects_controller.rb
  app/controllers/request_templates_controller.rb
  app/controllers/servers_controller.rb
  config/locales/en.yml
Labels: Review Required

#521 519/Edit Software of server
  app/controllers/servers_controller.rb
  app/views/servers/_form.html.erb
  spec/controllers/servers_controller_spec.rb
  spec/views/servers/new.html.erb_spec.rb
Labels: Review Required
