Repository hpi-swt2/vm-portal, pull requests merged in 2019-02, with the labels that each got.

#344 154/scaffold/beautify email notifications
  app/views/notification_mailer/notify_email.html.erb
  db/schema.rb
Labels: Review Required

#284 148/scaffold/Complete VM to responsable relation
  app/api/v_sphere/folder.rb
  app/api/v_sphere/virtual_machine.rb
  app/controllers/requests_controller.rb
  app/models/request.rb
  app/models/user.rb
  app/models/virtual_machine_config.rb
  app/views/errors/timeout.html.erb
  app/views/requests/_form.html.erb
  app/views/requests/show.html.erb
  config/routes.rb
  db/migrate/20190121160434_create_join_table_requests_responsible_users.rb
  db/migrate/20190201091109_create_join_table_virtual_machine_config_users.rb
  db/schema.rb
  spec/api/v_sphere_api_mocker.rb
  spec/api/v_sphere_api_spec.rb
  spec/controllers/requests_controller_spec.rb
  spec/controllers/vms_controller_spec.rb
  spec/end_to_end/end_to_end_spec.rb
  spec/factories/requests.rb
  spec/factories/virtual_machine_configs.rb
  spec/features/dashboard/dashboard_spec.rb
  spec/features/requests/accept_reject_request_spec.rb
  spec/models/request_spec.rb
  spec/models/virtual_machine_config_spec.rb
  spec/spec_helper.rb
  spec/views/requests/edit.html.erb_spec.rb
  spec/views/requests/index.html.erb_spec.rb
  spec/views/requests/show.html.erb_spec.rb
  spec/views/vms/show.html.erb_spec.rb
Labels: WIP

#350 154/scaffold/remaining beauty fixes
  app/views/notification_mailer/notify_email.html.erb
  db/schema.rb
Labels: Review Required

#352 Change request name regex
  app/models/request.rb
  spec/api/apiwrapper_spec.rb
  spec/controllers/vms_controller_spec.rb
  spec/features/requests/index.html.erb_spec.rb
  spec/models/request_spec.rb
  spec/views/vms/index.html.erb_spec.rb
  spec/views/vms/show.html.erb_spec.rb
Labels: Review Required

#353 remove remnants of old api from hosts
  app/api/v_sphere/host.rb
  app/api/v_sphere/virtual_machine.rb
  app/controllers/hosts_controller.rb
  app/views/hosts/show.html.erb
  spec/api/v_sphere_api_mocker.rb
  spec/controllers/hosts_controller_spec.rb
  spec/views/hosts/show.html.erb_spec.rb
Labels: WIP, team resource overview

#343 send notifications after various events
  app/controllers/projects_controller.rb
  app/controllers/users_controller.rb
  app/controllers/vms_controller.rb
  db/schema.rb
Labels: Review Required

#356 322/confirmation prompt before archiving
  app/views/vms/index.html.erb
  app/views/vms/show.html.erb
Labels: Review Required

#357 Fix/add users to vm pages
  app/controllers/requests_controller.rb
  app/models/request.rb
  app/views/vms/index.html.erb
  app/views/vms/show.html.erb
  config/routes.rb
  spec/controllers/requests_controller_spec.rb
  spec/end_to_end/end_to_end_spec.rb
  spec/models/request_spec.rb
Labels: Review Required

#365 304 - Tackles the webkit-issue by adding another POST-based route for logout
  app/views/application/_navbar.html.erb
  config/routes.rb
  db/schema.rb
  spec/features/sessions/user_sign_out_spec.rb
Labels: WIP

#267 238/vertical/import-update-puppet-scripts
  app/api/v_sphere/virtual_machine.rb
  app/controllers/application_controller.rb
  app/controllers/dashboard_controller.rb
  app/controllers/requests_controller.rb
  app/helpers/puppet_parser_helper.rb
  app/models/request.rb
  app/models/user.rb
  app/views/dashboard/index.html.erb
  app/views/servers/show.html.erb
  lib/git_helper.rb
  lib/puppetscript.rb
  spec/api/apiwrapper_spec.rb
  spec/api/v_sphere_api_mocker.rb
  spec/api/v_sphere_api_spec.rb
  spec/controllers/vms_controller_spec.rb
  spec/factories/users.rb
  spec/features/dashboard/dashboard_spec.rb
  spec/helpers/Node/node-example.pp
  spec/helpers/Node/node-example2.pp
  spec/helpers/Node/node-example3.pp
  spec/helpers/Node/node-example4.pp
  spec/helpers/Node/node-example5.pp
  spec/helpers/Node/node-example6.pp
  spec/helpers/Node/node-example7.pp
  spec/helpers/Node/node-example8.pp
  spec/helpers/puppet_parser_helper_spec.rb
  spec/models/request_spec.rb
  spec/models/user_spec.rb
  spec/spec_helper.rb
  spec/support/git_stub.rb
  spec/views/vms/index.html.erb_spec.rb
  spec/views/vms/show.html.erb_spec.rb
Labels: Review Required

#367 259/vertical/request page refactoring
  app/assets/javascripts/request.js
  app/assets/stylesheets/layout.scss
  app/assets/stylesheets/requests.scss
  app/controllers/requests_controller.rb
  app/models/request.rb
  app/views/requests/_form.html.erb
  app/views/requests/new.html.erb
  db/migrate/20190204164433_add_projects_to_requests.rb
  db/migrate/20190205115620_add_port_forwarding_to_requests.rb
  db/schema.rb
  spec/controllers/requests_controller_spec.rb
  spec/end_to_end/end_to_end_spec.rb
  spec/factories/requests.rb
  spec/views/requests/edit.html.erb_spec.rb
  spec/views/requests/index.html.erb_spec.rb
  spec/views/requests/new.html.erb_spec.rb
  spec/views/requests/show.html.erb_spec.rb
Labels: WIP

#394 Fix/double notifications
  app/controllers/requests_controller.rb
Labels: Review Required

#392 Move environment variables into ENV
  app/api/v_sphere/cluster.rb
  app/api/v_sphere/connection.rb
  app/api/v_sphere/host.rb
  app/api/v_sphere/virtual_machine.rb
  app/api/vmapi.rb
  app/controllers/hosts_controller.rb
  app/controllers/requests_controller.rb
  app/controllers/vms_controller.rb
  app/helpers/vms_helper.rb
  app/models/request.rb
  app/models/user.rb
  app/views/application/_navbar.html.erb
  app/views/hosts/show.html.erb
  config/environment_variables.example.yml
  config/routes.rb
  spec/api/apiwrapper_spec.rb
  spec/api/v_sphere_api_mocker.rb
  spec/api/v_sphere_api_spec.rb
  spec/controllers/dashboard_controller_spec.rb
  spec/controllers/vms_controller_spec.rb
Labels: WIP

#402 399/make settings configurable
  app/api/v_sphere/connection.rb
  app/api/v_sphere/virtual_machine.rb
  app/assets/helpers/hart_form_builder.rb
  app/assets/javascripts/app_settings.coffee
  app/assets/stylesheets/app_settings.scss
  app/controllers/app_settings_controller.rb
  app/controllers/vms_controller.rb
  app/helpers/app_settings_helper.rb
  app/models/app_setting.rb
  app/models/archivation_request.rb
  app/models/user.rb
  app/views/app_settings/_app_setting.json.jbuilder
  app/views/app_settings/_form.html.erb
  app/views/app_settings/edit.html.erb
  app/views/application/_navbar.html.erb
  config/application.rb
  config/environment_variables.example.yml
  config/environments/development.rb
  config/environments/production.rb
  config/environments/test.rb
  config/initializers/notification_mailer.rb
  config/routes.rb
  db/migrate/20190219095240_create_app_settings.rb
  db/schema.rb
  lib/git_helper.rb
  lib/puppetscript.rb
  spec/controllers/app_settings_controller_spec.rb
  spec/factories/app_settings.rb
  spec/helpers/app_settings_helper_spec.rb
  spec/models/app_setting_spec.rb
  spec/models/request_spec.rb
  spec/routing/app_settings_routing_spec.rb
  spec/spec_helper.rb
  spec/support/git_stub.rb
  spec/views/app_settings/edit.html.erb_spec.rb
  spec/views/application/_navbar.html.erb_spec.rb
Labels: Review Required

#414 400/configurable vSphere rootfolder
  .rubocop.yml
  app/api/v_sphere/connection.rb
  app/api/v_sphere/folder.rb
  app/assets/helpers/hart_form_builder.rb
  app/controllers/app_settings_controller.rb
  app/models/app_setting.rb
  app/views/app_settings/_form.html.erb
  db/migrate/20190222160517_addv_sphere_root_folder_to_app_settings.rb
  db/schema.rb
  spec/controllers/app_settings_controller_spec.rb
Labels: Review Required

#417 411/Add dynamic PuppetScript Settings
  app/api/v_sphere/virtual_machine.rb
  app/controllers/app_settings_controller.rb
  app/models/app_setting.rb
  app/models/request.rb
  app/models/user.rb
  app/views/app_settings/_form.html.erb
  app/views/vms/edit_config.html.erb
  db/migrate/20190224103931_add_git_puppet_settings.rb
  db/schema.rb
  lib/puppetscript.rb
  spec/lib/puppetscript_spec.rb
  spec/support/git_stub.rb
Labels: Review Required

#419 Upgrade to Bootstrap 4.3.1
  Gemfile
  Gemfile.lock
Labels: Review Required

#415 404/Make descriptions searchable
  app/views/vms/index.html.erb
Labels: Review Required

#434 429/Use button for back action
  app/views/requests/_form.html.erb
  app/views/requests/edit.html.erb
  app/views/requests/new.html.erb
  app/views/requests/show.html.erb
Labels: Review Required
