Repository hpi-swt2/vm-portal, pull requests merged in 2019-01, with the labels that each got.

#220 selecting a vm template
  app/assets/javascripts/request.js
  app/assets/stylesheets/requests.scss
  app/controllers/requests_controller.rb
  app/views/requests/_form.html.erb
  config/initializers/assets.rb
  db/schema.rb
  spec/features/requests/select_operating_system_spec.rb
  spec/views/requests/edit.html.erb_spec.rb
  spec/views/requests/new.html.erb_spec.rb
Labels: WIP

#183 99/scaffold/add user to vm request - after functionality
  Gemfile
  Gemfile.lock
  app/assets/javascripts/application.js
  app/assets/stylesheets/requests.scss
  app/controllers/requests_controller.rb
  app/controllers/vms_controller.rb
  app/models/request.rb
  app/views/requests/_form.html.erb
  app/views/requests/show.html.erb
  db/migrate/20181209184959_create_users_assigned_to_requests.rb
  db/migrate/20181216161526_add_application_name_to_requests.rb
  db/migrate/20181217204029_add_description_to_requests.rb
  db/schema.rb
  spec/controllers/requests_controller_spec.rb
  spec/factories/requests.rb
  spec/models/request_spec.rb
  spec/views/requests/edit.html.erb_spec.rb
  spec/views/requests/index.html.erb_spec.rb
  spec/views/requests/new.html.erb_spec.rb
  spec/views/requests/show.html.erb_spec.rb
  spec/views/vms/index.html.erb_spec.rb
Labels: WIP

#194 177 clean up Header
  app/assets/images/favicon.ico
  app/controllers/application_controller.rb
  app/views/application/_navbar.html.erb
  app/views/devise/sessions/new.html.erb
  app/views/layouts/application.html.erb
  spec/views/application/_navbar.html.erb_spec.rb
Labels: Review Required, team vertical

#266 255/oldies/redirect to page that triggered vm action
  app/controllers/vms_controller.rb
  spec/controllers/vms_controller_spec.rb
Labels: team resource overview

#248 Fix/improve vmapi
  app/api/v_sphere/connection.rb
  app/api/v_sphere/folder.rb
  app/api/v_sphere/virtual_machine.rb
  app/controllers/vms_controller.rb
  app/models/user.rb
  db/schema.rb
  spec/api/v_sphere_api_spec.rb
  spec/features/slack/slack_controller_spec.rb
Labels: Review Required, enhancement

#196 Add new Server Page
  app/assets/javascripts/servers.coffee
  app/assets/stylesheets/scaffolds.scss
  app/assets/stylesheets/servers.scss
  app/controllers/servers_controller.rb
  app/helpers/servers_helper.rb
  app/models/server.rb
  app/views/application/_navbar.html.erb
  app/views/servers/_form.html.erb
  app/views/servers/_server.json.jbuilder
  app/views/servers/edit.html.erb
  app/views/servers/index.html.erb
  app/views/servers/index.json.jbuilder
  app/views/servers/new.html.erb
  app/views/servers/show.html.erb
  app/views/servers/show.json.jbuilder
  config/routes.rb
  db/migrate/20190111102059_create_servers.rb
  db/schema.rb
  spec/controllers/servers_controller_spec.rb
  spec/factories/servers.rb
  spec/helpers/servers_helper_spec.rb
  spec/models/server_spec.rb
  spec/requests/servers_spec.rb
  spec/routing/servers_routing_spec.rb
  spec/views/application/_navbar.html.erb_spec.rb
  spec/views/servers/edit.html.erb_spec.rb
  spec/views/servers/index.html.erb_spec.rb
  spec/views/servers/new.html.erb_spec.rb
  spec/views/servers/show.html.erb_spec.rb
Labels: 13 pain points, WIP

#265 Fix/use new vsphere api
  app/controllers/vms_controller.rb
  app/views/vms/index.html.erb
  spec/api/v_sphere_api_helper.rb
  spec/api/v_sphere_api_spec.rb
  spec/controllers/vms_controller_spec.rb
  spec/views/vms/index.html.erb_spec.rb
Labels: Review Required, enhancement

#278 Use new vSphere-API for dashboard
  app/api/v_sphere/cluster.rb
  app/api/v_sphere/connection.rb
  app/api/v_sphere/folder.rb
  app/api/v_sphere/host.rb
  app/api/v_sphere/virtual_machine.rb
  app/controllers/dashboard_controller.rb
  app/views/dashboard/index.html.erb
  app/views/servers/_server.json.jbuilder
  app/views/servers/index.json.jbuilder
  app/views/servers/show.json.jbuilder
  spec/api/v_sphere_api_mocker.rb
  spec/api/v_sphere_api_spec.rb
  spec/controllers/vms_controller_spec.rb
  spec/spec_helper.rb
  spec/views/vms/index.html.erb_spec.rb
Labels: Review Required

#236 UI Refactoring
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/layout.scss
  app/assets/stylesheets/notifications.scss
  app/assets/stylesheets/requests.scss
  app/assets/stylesheets/vms.scss
  app/views/application/_footer.html.erb
  app/views/application/_navbar.html.erb
  app/views/dashboard/index.html.erb
  app/views/devise/sessions/new.html.erb
  app/views/errors/not_found.html.erb
  app/views/errors/timeout.html.erb
  app/views/hosts/index.html.erb
  app/views/hosts/show.html.erb
  app/views/layouts/application.html.erb
  app/views/notifications/_list.html.erb
  app/views/operating_systems/index.html.erb
  app/views/operating_systems/new.html.erb
  app/views/projects/_form.html.erb
  app/views/projects/_list.html.erb
  app/views/projects/edit.html.erb
  app/views/projects/index.html.erb
  app/views/projects/show.html.erb
  app/views/request_templates/_form.html.erb
  app/views/request_templates/index.html.erb
  app/views/request_templates/new.html.erb
  app/views/requests/_form.html.erb
  app/views/requests/index.html.erb
  app/views/requests/new.html.erb
  app/views/requests/show.html.erb
  app/views/servers/index.html.erb
  app/views/users/index.html.erb
  app/views/users/show.html.erb
  app/views/vms/index.html.erb
  app/views/vms/new.html.erb
  app/views/vms/show.html.erb
  spec/features/projects/index.html.erb_spec.rb
  spec/views/vms/index.html.erb_spec.rb
Labels: WIP

#338 154/scaffold/email notifications
  app/controllers/users_controller.rb
  app/mailers/application_mailer.rb
  app/mailers/notification_mailer.rb
  app/models/user.rb
  app/views/notification_mailer/notify_email.html.erb
  app/views/notification_mailer/notify_email.text.erb
  app/views/users/show.html.erb
  config/environments/development.rb
  db/migrate/20190129184200_add_email_notifications_to_user.rb
  db/schema.rb
  spec/mailers/notification_mailer_spec.rb
  spec/mailers/previews/notification_mailer_preview.rb
Labels: WIP, team scaffold

#339 Add os to vm config edit page
  app/helpers/requests_helper.rb
  app/helpers/vms_helper.rb
  app/views/vms/edit_config.html.erb
  spec/controllers/requests_controller_spec.rb
  spec/factories/requests.rb
  spec/helpers/requests_helper_spec.rb
  spec/helpers/vms_helper_spec.rb
  spec/models/request_spec.rb
  spec/views/requests/edit.html.erb_spec.rb
  spec/views/requests/index.html.erb_spec.rb
  spec/views/requests/new.html.erb_spec.rb
  spec/views/requests/show.html.erb_spec.rb
  spec/views/vms/edit_config.html.erb_spec.rb
Labels: Review Required

#330 update requests list
  app/assets/javascripts/application.js
  app/assets/javascripts/prevent_anchor_reload.js
  app/assets/stylesheets/layout.scss
  app/assets/stylesheets/vms.scss
  app/controllers/requests_controller.rb
  app/controllers/vms_controller.rb
  app/views/hosts/show.html.erb
  app/views/requests/index.html.erb
  app/views/servers/show.html.erb
  app/views/vms/index.html.erb
  app/views/vms/show.html.erb
  spec/api/v_sphere_api_mocker.rb
  spec/views/hosts/show.html.erb_spec.rb
  spec/views/requests/index.html.erb_spec.rb
  spec/views/vms/index.html.erb_spec.rb
  spec/views/vms/show.html.erb_spec.rb
Labels: Review Required

#331 326/scaffold/sudo users not stored
  Gemfile.lock
  app/controllers/requests_controller.rb
  app/models/request.rb
  app/views/requests/_form.html.erb
  db/schema.rb
  spec/controllers/requests_controller_spec.rb
  spec/features/dashboard/dashboard_spec.rb
  spec/models/request_spec.rb
Labels: Review Required

#341 fix puppet script icon
  app/assets/stylesheets/vms.scss
Labels: Review Required

#335 hosts routes and button show only if user is admin
  app/controllers/hosts_controller.rb
  app/views/application/_navbar.html.erb
  spec/controllers/hosts_controller_spec.rb
  spec/views/application/_navbar.html.erb_spec.rb
Labels: WIP
